extends: ['./.eslintrc.yml', 'plugin:@typescript-eslint/eslint-recommended']
parser: '@typescript-eslint/parser'
rules:
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-use-before-define': 'off'
