export const ActionType = {
  SET_GENRE: `SET_GENRE`,
  SET_FILTRING_MOVIES_BY_GENRE: `SET_FILTRING_MOVIES_BY_GENRE`,
  INCREASE_DISPLAYED_MOVIES_COUNT: `INCREASE_DISPLAYED_MOVIES_COUNT`,
  RESET_DISPLAYED_MOVIES_COUNT: `RESET_DISPLAYED_MOVIES_COUNT`,
  LOAD_MOVIE: `LOAD_MOVIE`,
  LOAD_MOVIES: `LOAD_MOVIES`,
  LOAD_FAVORITE_MOVIES: `LOAD_FAVORITE_MOVIES`,
  REQUIRED_AUTHORIZATION: `REQUIRED_AUTHORIZATION`,
  CHECK_ERROR_AUTHORIZATION: `CHECK_ERROR_AUTHORIZATION`,
  LOAD_REVIEWS: `LOAD_REVIEWS`,
  CHECK_IS_DATA_SENDING: `CHECK_IS_DATA_SENDING`,
  CHECK_IS_ERROR_LOADING: `CHECK_IS_ERROR_LOADING`,
  GET_USER_INFO: `GET_USER_INFO`,
};

export const ALL_GENRES = `All genres`;
export const DISPLAYED_MOVIES_CARDS = 8;

export const ReviewLength = {
  MIN: 50,
  MAX: 400
};

export const RATING_COUNT = 5;
export const RATING_DEFAULT = 0;

export const AppRoute = {
  LOGIN: `/login`,
  MY_LIST: `/my-list`,
  ROOT: `/`,
  MOVIE_CARD: `/film`,
  PLAYER: `/player`,
  REVIEW: `/review`,
};

