export const ActionType = {
  SET_GENRE: `SET_GENRE`,
  SET_FILTRING_MOVIES_BY_GENRE: `SET_FILTRING_MOVIES_BY_GENRE`,
  INCREASE_DISPLAYED_MOVIES_COUNT: `INCREASE_DISPLAYED_MOVIES_COUNT`,
  RESET_DISPLAYED_MOVIES_COUNT: `RESET_DISPLAYED_MOVIES_COUNT`,
  CHOOSE_MOVIE: `CHOOSE_MOVIE`,
  PLAY_MOVIE: `PLAY_MOVIE`,
  CLOSE_MOVIE: `CLOSE_MOVIE`,
};

export const ALL_GENRES = `All genres`;
export const DISPLAYED_MOVIES_CARDS = 8;

